### ISSUE TITLE
[BUG] PR_END_OF_FILE_ERROR with docker production configuration

### ISSUE THREAD

**Issue by falisca** [lanedirt/OGameX#196]
**Describe the bug**
Basically trying tu run the docker production config when I visit the login page (in a local environment) I receive this error with FireFox and similar error page with Chrome.
"PR_END_OF_FILE_ERROR, connection has been closed".
I consider normal that visiting localhost I get redirected to localhost/login but the connections is closed 2 to security reasons. I suppose that the SSL certs must be configured but I do not know how.
I changed only db password from the .env )production) file and then run steps from the readme, docker production section.
I tried also adding "TRUSTED_HOSTS" to env file, copy-pasted from an'other laravel project I've seen some days ago but without really knowing what I was doing :)
Someone on stackoverflow sudgested to run "php artisan optimize" before "serve" (using Laravel versions prior to 5.5) but In production the serve command is not needed (not mentioned in the steps) and running optimize command didn't changed nothing any way.
Sorry I'm not so familiar with Laravel.
Some advice?

**To Reproduce**
1. copy .env.example_prod to .env and modify db password
2. run docker compose stack as README steps (section B: production - docker)
3. execute compose and php commands as shown in the README
Note that when running "php artisan key:generate" command is required to type or select "yes" or "no" when asked, this is different from the development installation that do not requires to accept.
5. open http://localhost/  you get redirected to localhost/login and the error is shown (using FF the error is "PR_END_OF_FILE_ERROR", with Chrome the error is less specific: "connection was unespectedly closed by the server").

**Expected behavior**
Opening the url of the login/register main page you'll get on the standard main page and not get blocked by a configuration error.

**Screenshots**

**Additional context**

**Comment by lanedirt** [comment]
Hi @falisca, thanks for the bug report!

I looked into it and you are right, the current config didn't work for the production build. What happened is that the production config forces the application to be accessed via HTTPS, however the local nginx config only exposed port 80. So that's why it gave this error.

The old config however did work for https://release.ogamex.dev, but that server has another reverse-proxy loadbalancer in front of it which handles the SSL certificate and proxies to the actual docker server via port 80.

I fixed this issue by updating the server config and have just pushed the commits. It works on my local machine now.

When you clone the repo again and execute the steps in the README.md, it should work now. You may get a SSL warning in your browser, but that is to be expected because it runs with a self-signed certificate. You can simple click the error away and ignore it.

Can you let me know if it works on your side too now?
