### ISSUE TITLE
[BUG] time_last_update incorrectly updated for all player planets

### ISSUE THREAD

**Issue by Jbaukens** [lanedirt/OGameX#313]
**Summary**: When a player is interacting with their homeworld, the `time_last_update` field is being erroneously updated for all of the player's planets instead of just the current planet. This results in an incorrect display of activity across the galaxy view, espionnage reports, where all planets are shown as active even though the player is only interacting with their homeworld.

**Expected Behavior**: The `time_last_update` field should only be updated for the planet where the player is currently active. Other planets should not have their database row modified unless the player or a specific mission interacts with them directly.

**Actual Behavior**: The `time_last_update` field is being updated for all of the player's planets regardless of which planet the player is interacting with. This causes all planets to appear active in the galaxy view, misleadingly indicating that the player is active on multiple planets simultaneously.

Steps to Reproduce:

1. Log into the game and navigate to the homeworld.
2. Perform an action that triggers an update (e.g., refresh page, resource collection, building, or unit movement).
3. Check the `time_last_update` for all player-owned planets.
4. Observe that all planets have their information updated, not just the homeworld.

**Comment by lanedirt** [comment]
Ah yes, good point! The culprit seems to be in GlobalGame.php, this middleware gets called on every page load and updates all user planets via `PlanetListService::update()`.

With what we know now this is incorrect: only the current selected planet of the user should be updated, not all of them. Making this change should not cause any issues because whenever the user switches to another planet that planet gets immediately updated so there shouldn't be any problem with old data showing.

Luckily this is a small change. I'll fix it right now.
