### ISSUE TITLE
[BUG] Discord Links are invalid 

### ISSUE THREAD

**Issue by jackbayliss** [lanedirt/OGameX#382]
**Describe the bug**
README Discord links are no longer valid, noticed when clicking on it I just get an expired link. 

Raising as it may be the preferred communication place for some people? 😄

**Comment by lanedirt** [comment]
Thanks for letting me know! I updated the invite URL in the readme, this one should now work.

It's weird though because when creating the old link I remember specifically setting it to "Not expire", but perhaps I still made a misclick. The new one should not expire anymore, so let's hope it doesn't this time.
