### ISSUE TITLE
[BUG] Building more than one Solar Satellite on the Resources page doesn't work

### ISSUE THREAD

**Issue by gabrieltsants** [lanedirt/OGameX#405]
**Description**
When attempting to build more than one Solar Satellite, only one is added to the build queue.

**To Reproduce**
1. Go to the 'Resources' page
2. Set more than one Solar Satellite to build
3. Click "Build"
4. Only one Solar Satellite will be queued for construction

**Expected behavior**
The specified number of Solar Satellites should be added to the build queue.

**Comment by lanedirt** [comment]
Hi @gabrieltsants,

Thank you for reporting this issue. 👍  I can confirm it on my local version as well. It seems to be related to the resources page. The `solar satellite` object is a bit of a special case, as this unit can be built from both the `resources` page and the `shipyard` page.

When I try to build multiple solar satellites from the shipyard page, it works fine. Therefore, I believe the resources page is missing a check that fails to properly handle or respect the quantity field.

Additionally, I noticed that the solar satellite image does not display correctly when built from the resources page. Please see the screenshot for reference:
<img width="216" alt="Screenshot 2024-10-20 at 19 58 01" src="https://github.com/user-attachments/assets/b2ca9388-ff6c-434f-a5a2-60fe448d119b">

**Comment by gabrieltsants** [comment]
Hi @lanedirt,

I noticed that the image issue also happens with the HyperSpace Drive.
![image](https://github.com/user-attachments/assets/204a3f08-25d8-4c10-8e62-e6db6e71fc8c)

Also, I’m not sure about the base version of the game, but the remaining time is the same for all three counters. In the screenshot above, you can see both the image error and the same countdown for all, **11m 12s**.

Regarding the Solar Satellite issue, I’ve been digging into the code and found that the Solar Satellite object is being treated as a Resource instead of a Ship. I started working on a fix, but I discovered there are many other areas that would need to be changed to make it work correctly. I have a lot of demands in my work at the moment, but as soon as I have more free time, I’ll continue looking into a solution. 😁

**Comment by lanedirt** [comment]
Hi @gabrieltsants,

The timer which is the same for all three counters looks to me like a bug. Maybe this is a regression caused by a recent change. Feel free to open up a new issue for this if you can reproduce it, haven't tried it yet myself.

And thanks for looking further into the issue. The `solar satellite` is indeed a "strange" game object in the sense that this is the only object (that I know of) that can be built from both the resources and shipyard page. So if you find workarounds in the code this is probably the reason.

I'll assign this issue to you. 👍  If you have any questions in the meantime feel free to update the issue. And of course work comes first, so no pressure 😄 !

**Comment by gabrieltsants** [comment]
Hi @lanedirt,

I noticed that the units are not in the Model, and the request during the unit build brings the following data:

```javascript
technologyId: technologyId,
amount: amount ? amount : 1,
mode: mode ? mode : 1,
_token: token
```

Do you think it's feasible to perform the validation by ID only in the AbstractBuildingsController? I created a validation this way, and it’s already available in my fork: [a0c0521](https://github.com/gabrieltsants/OGameX/commit/a0c05214df51e3d6c9adf4cf73878b81f99d857d).

I considered standardizing the `addBuildRequest` method to cover the other controllers that are quite similar, but I was concerned about adding complexity to the code or breaking some rule that I might not be aware of.

**Comment by lanedirt** [comment]
Hi @gabrieltsants,

The solution in your fork looks like a nice and simple way to me to solve this issue. Smart! 👍 

Since the `solar satellite` is the only object in the game that has this weird quirk in that it can be built from two categories, adding that `if` check there makes sense to me. So +1 from me 😄 !

**Comment by gabrieltsants** [comment]
Hi @lanedirt,

Thanks for the feedback!

I’ll go ahead and submit the pull request.

**Comment by aDwCarrazzone** [comment]
After merging to the main branch, the Solar Satellite construction process appears to function inconsistently. While the requested satellites are built, the displayed data does not update correctly unless the page is manually refreshed. Furthermore, the game appears to be mismanaging queues, building more satellites than requested and using the Building queue instead of the Shipyard queue for the construction process. For example, if a user has 180 Solar Satellites and builds 1 more:

- The count should increase to 181 and only 1 unit should be built.
- Instead, 2 units are built, and the count incorrectly updates to 182.

**Comment by lanedirt** [comment]
Hi @aDwCarrazzone, thanks for testing it and giving your feedback. I noticed the same after the merge. I'm already working on fixing this in:

- #457 

This will fix the wrong queue display and the +1 units built bug.

**Comment by lanedirt** [comment]
All reported issues are now fixed and it should now work like in the official game. The changes have just been merged into main. If you still run into issues please let me know 🙌 !
